# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election-data.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'election-data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65lection-data.proto\"C\n\x0f\x45lectionRequest\x12\x17\n\x06region\x18\x01 \x01(\x0b\x32\x07.Region\x12\x17\n\x07parties\x18\x02 \x03(\x0b\x32\x06.Party\"\"\n\x10\x45lectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x88\x01\n\x06Region\x12\x10\n\x08regionID\x18\x01 \x01(\x05\x12\x12\n\nregionName\x18\x02 \x01(\t\x12\x15\n\rregionAddress\x18\x03 \x01(\t\x12\x18\n\x10regionPostalCode\x18\x04 \x01(\t\x12\x14\n\x0c\x66\x65\x64\x65ralState\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"-\n\x05Party\x12\x0f\n\x07partyID\x18\x01 \x01(\t\x12\x13\n\x0b\x61mountVotes\x18\x02 \x01(\x05\x32N\n\x13\x45lectionDataService\x12\x37\n\x10sendElectionData\x12\x10.ElectionRequest\x1a\x11.ElectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=23
  _globals['_ELECTIONREQUEST']._serialized_end=90
  _globals['_ELECTIONRESPONSE']._serialized_start=92
  _globals['_ELECTIONRESPONSE']._serialized_end=126
  _globals['_REGION']._serialized_start=129
  _globals['_REGION']._serialized_end=265
  _globals['_PARTY']._serialized_start=267
  _globals['_PARTY']._serialized_end=312
  _globals['_ELECTIONDATASERVICE']._serialized_start=314
  _globals['_ELECTIONDATASERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
